### ISSUE TITLE
Pre-trained model

### ISSUE THREAD

**Issue by GlebSBrykin** [JianqiangRen/AAMS#1]
Wonderful project! Can you place the pre-trained model you used?

**Comment by JianqiangRen** [comment]
Our pre-trained model has been uploaded, please find it under  tf_model folder.

**Comment by JianqiangRen** [comment]
> Wonderful project! Can you place the pre-trained model you used?

Our pre-trained model has been uploaded, please find it under tf_model folder.

**Comment by GlebSBrykin** [comment]
Thanks!
