### ISSUE TITLE
Program is too  slow

### ISSUE THREAD

**Issue by adaxidedakaonang** [JianqiangRen/AAMS#10]
I run your program with RTX 2080Ti and the time consumption is about 500 S. The content size is (800,800,3), style size is (512,512,3), and the attention size is (1,100,100,512).

**Comment by adaxidedakaonang** [comment]
The tested time is about code "sess.run()" in test.py

**Comment by JianqiangRen** [comment]
Maybe there is some problem with your environment?    I have never met this before, even with only CPU,   500s for one images is inconceivable

**Comment by adaxidedakaonang** [comment]
New test result is : a image with size of 512X512 cost 1.2S。在进行1024图像比较时，程序会改变图像大小至800？，运行时间为1.5S
