### ISSUE TITLE
about the freeze_model.py

### ISSUE THREAD

**Issue by hello-trouble** [JianqiangRen/AAMS#2]
hello, Thank you for you excellent paper of CVPR2019. I am puzzled about the freeze_model.py .Could it deal with batch images in our project.Both the freeze_model.py and test.py  only transfer one image ?  Thank you for your help!

**Comment by hello-trouble** [comment]
when I run the train.py,  an error of "TypeError: 'numpy.float32' object is not iterable" occured, but I don't change the origin code , do you meet this problem ?

**Comment by JianqiangRen** [comment]
> hello, Thank you for you excellent paper of CVPR2019. I am puzzled about the freeze_model.py .Could it deal with batch images in our project.Both the freeze_model.py and test.py only transfer one image ? Thank you for your help!

Yes, after frozen, the model could only handle one pair of images(content/style image) in one fowrard process, since there may be different on sizes  among batch images

**Comment by JianqiangRen** [comment]
> when I run the train.py, an error of "TypeError: 'numpy.float32' object is not iterable" occured, but I don't change the origin code , do you meet this problem ?

I haven't met the problem you mentioned, please check your env, our project requests
 Python (version 2.7)
Tensorflow (>=1.4)
Numpy
Matplotlib
