### ISSUE TITLE
关于test时传入的inter_weight参数的理解

### ISSUE THREAD

**Issue by byby221b** [JianqiangRen/AAMS#4]
您好，首先非常感谢您的工作。
我在阅读代码时注意到，与train的过程略有不同，在test过程中，decoder的输入是priojected_content_feature和fused_feature的线性平均，inter_weight是线性平均的权重，请问这一实现的目的是什么呢？在论文中是否有提及呢？
期待您的回复。

**Comment by JianqiangRen** [comment]
Thank you for your attention. inter_weight is used to control the level of stylization,  see Figure 12 in https://arxiv.org/pdf/1901.05127.pdf for intuitive understanding.

**Comment by byby221b** [comment]
Thanks a lot! It was my negligence that I did not read the appendix carefully.
