### ISSUE TITLE
Questions about freeze_model.py

### ISSUE THREAD

**Issue by zq-hznu** [JianqiangRen/AAMS#8]
Hello,brother!When I run freeze_model.py,it causes errors like "TypeError: 'Tensor' objects are not iterable when eager execution is not enabled.To iterate over this tensor use 'tf.map_fn' ". I tried to modify many times,but I failed.I'm so distressed .Can you help me?
Thank you very much!

**Comment by JianqiangRen** [comment]
> Hello,brother!When I run freeze_model.py,it causes errors like "TypeError: 'Tensor' objects are not iterable when eager execution is not enabled.To iterate over this tensor use 'tf.map_fn' ". I tried to modify many times,but I failed.I'm so distressed .Can you help me?
> Thank you very much!

Please check the version of your tensorflow
